services:
  shadowbox:
    image: diffusehyperion/outline-vpn
    container_name: shadowbox
    restart: unless-stopped
    volumes:
      - shadowbox-state:/shadowbox/state
    environment:
      - SB_STATE_DIR=/shadowbox/state
      - SB_API_PREFIX=api
      - SB_CERTIFICATE_FILE=/shadowbox/state/shadowbox-selfsigned.crt
      - SB_PRIVATE_KEY_FILE=/shadowbox/state/shadowbox-selfsigned.key
    ports:
      - 8082:8082
      - 8082:8082/udp
      # - 8081:8081 Port for access key management API. Not necessary for running


networks:
  default:
    name: outline-vpn

volumes:
  shadowbox-state:
    name: shadowbox-state